image: circleci/php:7.2-cli
stages:
  - build
  - inspect
cache:
  paths:
    - vendor
    - ~/.composer/cache

before_script:
  - echo 'memory_limit=-1' | tee -a /usr/local/etc/php/php.ini

build:
  stage: build
  before_script:
    - apt-get install libpng-dev -y
    - docker-php-ext-install gd
    - composer -n global require -n "hirak/prestissimo"
  script: composer install -n --prefer-dist
  artifacts:
    paths:
      - bin
      - vendor
      - web

address:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/address
  allow_failure: true