image: circleci/php:7.2-cli
stages:
  - build
  - inspect
cache:
  paths:
    - vendor
    - ~/.composer/cache

before_script:
  - echo 'memory_limit=-1' | sudo tee -a /usr/local/etc/php/php.ini

build:
  stage: build
  before_script:
    - sudo apt-get install libpng-dev -y
    - sudo docker-php-ext-install gd
    - composer -n global require -n "hirak/prestissimo"
  script: composer install -n --prefer-dist
  artifacts:
    paths:
      - bin
      - vendor
      - web

address:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/address --no-progress
commerce:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/commerce --no-progress
entity:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/entity --no-progress
entity_reference_revisions:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/entity_reference_revisions --no-progress
inline_entity_form:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/inline_entity_form --no-progress
profile:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/profile --no-progress
state_machine:
  stage: inspect
  script: ./vendor/bin/phpstan analyse web/modules/contrib/state_machine --no-progress