
stages:
  - build
  - inspect

before_script:
  image: circleci/php:7.2-cli
  before_script:
    - sudo apt-get install libpng-dev -y
    - sudo docker-php-ext-install gd
    - echo 'memory_limit=-1' | sudo tee -a /usr/local/etc/php/php.ini
    - composer -n global require -n "hirak/prestissimo"
    - composer install -n --prefer-dist

address:
  script: ./vendor/bin/phpstan analyse web/modules/contrib/address